Учебный проект: нас орда
htmlacademy-javascript/1550703-code-and-magick-21 pull request #4
Opened 2020-10-01 15:16 UTC by rmaidveo

---
:mortar_board: [Учебный проект: нас орда](https://up.htmlacademy.ru/javascript/21/user/1550703/tasks/6)

:boom: https://htmlacademy-javascript.github.io/1550703-code-and-magick-21/4/

2020-10-03 17:38 UTC, StolpnerA requested changes

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +var EYES_COLOR = ['black', 'red', 'blue', 'yellow', 'green'];
Для читаемости хорошо бы каждый элемент массива с новой строки. Обычно в одну строку пишется когда массив из 1, 2 элементов. Дальше скидывается вниз

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +userDialog.classList.remove(`hidden`);
В функцию давай, как минимум 1 пункт задания = 1 функция

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +var generateArray = function () {
Функция называется `generateArray`, а по сути генерирует объект :) Давай исправим

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +userDialog.classList.remove(`hidden`);
Ты же уже это сделала на 8 строке

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +similarListElement.appendChild(renderWizardList(wizardList));
Давай в функцию

2020-10-03 17:38 UTC, StolpnerA commented on js/setup.js
> +userDialog.querySelector(`.setup-similar`).classList.remove(`hidden`);
В отдельную функцию плиз

2020-10-03 17:39 UTC, StolpnerA commented
И давай разделять код пустыми строками, на логически блоки, для читаемости. На такое не жалей строчки кода ;)

Обычно разделяются какие-то импорты/экспорты, объявления переменных, функции между собой, бывает даже выделение внутри функции, например циклы и т.п.

2020-10-04 19:50 UTC, StolpnerA commented
Еще 2-а коммента остались :)

2020-10-05 15:01 UTC, rmaidveo commented
@StolpnerA обновила и вроде все , но нашла только один, что второе?

2020-10-07 22:06 UTC, merged